#pragma once

#define WINDOW_TITLE "GAME XA THU"
#define WINDOW_HEIGHT 720
#define WINDOW_WIDTH 1280

#define MAX_BACK_SLOT 8
#define MAX_BACK_UNIT_PER_LINE 4
#define MAX_BACK_UNIT_PER_SLOT 12

#define MAX_MAIN_SLOT 8
#define MAX_MAIN_UNIT_PER_LINE 10
#define MAX_MAIN_UNIT_PER_SLOT 30

#define MAX_FLANK_SLOT 3
#define MAX_FLANK_UNIT_PER_LINE 10
#define MAX_FLANK_UNIT_PER_SLOT 20

#define LINES_PER_SLOT 3
#define LINES_PER_SLOT_FLANK 2

#define DISTANCE_BETWEEN_SLOT 20
#define X_DISTANCE_BETWEEN_UNIT 5
#define Y_DISTANCE_BETWEEN_UNIT 40
#define UNIT_HEIGHT WINDOW_HEIGHT / 20

#define Y_DISTANCE_BETWEEN_FIELD 100
#define Y_DISTANCE_BETWEEN_FIELD_AND_SCREEN 20